<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Continue</name>
   <tag></tag>
   <elementGuidId>c1236ce1-8ff3-4d2f-abd7-164cf423707e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Continue')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.primary-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://localhost:8080/?loginToken=MDAxOGxvY2F0aW9uIG1hdHJpeC5vcmcKMDAxM2lkZW50aWZpZXIga2V5CjAwMTBjaWQgZ2VuID0gMQowMDIzY2lkIHVzZXJfaWQgPSBAaXIxczptYXRyaXgub3JnCjAwMTVjaWQgdHlwZSA9IGxvZ2luCjAwMWRjaWQgdGltZSA8IDE2NDI0MzEyODQzODQKMDAyN2NpZCBhdXRoX3Byb3ZpZGVyX2lkID0gb2lkYy1nb29nbGUKMDAyZnNpZ25hdHVyZSDHv9GJ7_wPk90-BGRcYynPebj--TXy3f0bEsys6IissAo#/</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>primary-button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/a[@class=&quot;primary-button&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Continue')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='http://localhost:8080/'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='@ir1s:matrix.org'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('/html[1]/body[1]/main[1]/a[@class=', '&quot;', 'primary-button', '&quot;', ']')])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continue']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://localhost:8080/?loginToken=MDAxOGxvY2F0aW9uIG1hdHJpeC5vcmcKMDAxM2lkZW50aWZpZXIga2V5CjAwMTBjaWQgZ2VuID0gMQowMDIzY2lkIHVzZXJfaWQgPSBAaXIxczptYXRyaXgub3JnCjAwMTVjaWQgdHlwZSA9IGxvZ2luCjAwMWRjaWQgdGltZSA8IDE2NDI0MzEyODQzODQKMDAyN2NpZCBhdXRoX3Byb3ZpZGVyX2lkID0gb2lkYy1nb29nbGUKMDAyZnNpZ25hdHVyZSDHv9GJ7_wPk90-BGRcYynPebj--TXy3f0bEsys6IissAo#/']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='@cung:matrix.org'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://localhost:8080/?loginToken=MDAxOGxvY2F0aW9uIG1hdHJpeC5vcmcKMDAxM2lkZW50aWZpZXIga2V5CjAwMTBjaWQgZ2VuID0gMQowMDIzY2lkIHVzZXJfaWQgPSBAY3VuZzptYXRyaXgub3JnCjAwMTVjaWQgdHlwZSA9IGxvZ2luCjAwMWRjaWQgdGltZSA8IDE2NDI0MzA5MDg5MTMKMDAyOWNpZCBhdXRoX3Byb3ZpZGVyX2lkID0gb2lkYy1mYWNlYm9vawowMDJmc2lnbmF0dXJlIGPRDYezvFpTldBBreUZkEFoc2cXq4fC4ufVTvmuD_spCg#/']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://localhost:8080/?loginToken=MDAxOGxvY2F0aW9uIG1hdHJpeC5vcmcKMDAxM2lkZW50aWZpZXIga2V5CjAwMTBjaWQgZ2VuID0gMQowMDIzY2lkIHVzZXJfaWQgPSBAY3VuZzptYXRyaXgub3JnCjAwMTVjaWQgdHlwZSA9IGxvZ2luCjAwMWRjaWQgdGltZSA8IDE2NDI0MzA4MjUzNTgKMDAyOWNpZCBhdXRoX3Byb3ZpZGVyX2lkID0gb2lkYy1mYWNlYm9vawowMDJmc2lnbmF0dXJlICf3W9joWkyqqsZnmoXC--h7CzL5r7WrAm9uM6bg4sr8Cg#/']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='@1ris:matrix.org'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://localhost:8080/?loginToken=MDAxOGxvY2F0aW9uIG1hdHJpeC5vcmcKMDAxM2lkZW50aWZpZXIga2V5CjAwMTBjaWQgZ2VuID0gMQowMDIzY2lkIHVzZXJfaWQgPSBAMXJpczptYXRyaXgub3JnCjAwMTVjaWQgdHlwZSA9IGxvZ2luCjAwMWRjaWQgdGltZSA8IDE2NDI0Mjg2MTMxNDIKMDAyN2NpZCBhdXRoX3Byb3ZpZGVyX2lkID0gb2lkYy1nb29nbGUKMDAyZnNpZ25hdHVyZSAHO3appXaE8CZLCYstSHDppAzmvDeo9ZPr4VUpUoSJgAo#/']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://localhost:8080/?loginToken=MDAxOGxvY2F0aW9uIG1hdHJpeC5vcmcKMDAxM2lkZW50aWZpZXIga2V5CjAwMTBjaWQgZ2VuID0gMQowMDIzY2lkIHVzZXJfaWQgPSBAaXIxczptYXRyaXgub3JnCjAwMTVjaWQgdHlwZSA9IGxvZ2luCjAwMWRjaWQgdGltZSA8IDE2NDI0Mjc4MjY2MTcKMDAyN2NpZCBhdXRoX3Byb3ZpZGVyX2lkID0gb2lkYy1nb29nbGUKMDAyZnNpZ25hdHVyZSAep_d6-3DLOf7ITMN2KGkzM_0CwIiAsLDWfh4Yg5xmnwo#/']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='@signup_git:matrix.org'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://localhost:8080/?loginToken=MDAxOGxvY2F0aW9uIG1hdHJpeC5vcmcKMDAxM2lkZW50aWZpZXIga2V5CjAwMTBjaWQgZ2VuID0gMQowMDI5Y2lkIHVzZXJfaWQgPSBAc2lnbnVwX2dpdDptYXRyaXgub3JnCjAwMTVjaWQgdHlwZSA9IGxvZ2luCjAwMWRjaWQgdGltZSA8IDE2NDIzNjMxOTY3MzEKMDAyN2NpZCBhdXRoX3Byb3ZpZGVyX2lkID0gb2lkYy1naXRodWIKMDAyZnNpZ25hdHVyZSCDR4H-Dqh2SKTyOCCqZUqc29F9IziHSUcmOC9yxUjN5wo']</value>
   </webElementXpaths>
</WebElementEntity>
